In [1]:
from __future__ import division
import matplotlib.pyplot as plt
get_ipython().magic(u'matplotlib inline')
import numpy as np
import scipy as sp
import scipy.linalg
import time
import random
import tensorflow as tf
from termcolor import colored
def print_np(x):
    print ("Type is %s" % (type(x)))
    print ("Shape is %s" % (x.shape,))
    print ("Values are: \n%s" % (x))

In [2]:
from model import unicycle
from cost import tracking
from iLQR import iLQR
from poliOpt import poliOpt
from appPoliOpt import appPoliOpt
from trajOpt import trajOpt
from policyClass import localPolicy
from modelLearn import localModelLearn, localPolicyLearn
from gps_util import getCostNN, getCostAppNN, getCostTraj, getObs, getDesired, getPlot

In [3]:
myPolicy = appPoliOpt('unicycle',100,5000,0.01,3,2,100)

In [4]:
myPolicy.setEnv(200,0.01)

In [5]:
# data generation
K = np.zeros((2,3))
k = np.ones((2,1))
K[0,0] = 1
K[1,0] = 2
K[0,1] = 1
K[1,1] = 2
K[0,2] = 4
K[1,2] = 3
k[0] = 1
k[1] = 2
x = np.random.uniform(-10,10,(3,100))
u = np.matmul(K,x) + k + np.random.randn(2,100)*0.05

In [6]:
myPolicy.setEnv(200,0.001)
myPolicy.update(x.transpose(),u.transpose(),1)

epoch 1, Training Loss= 528.077159
epoch 41, Training Loss= 0.327910
epoch 81, Training Loss= 0.190394
epoch 121, Training Loss= 0.157399
epoch 161, Training Loss= 0.140455
Optimization - approximated policy is optimized


In [7]:
a = myPolicy.jacobian(x[:,0:10].transpose())

In [8]:
print K
print_np(a)

[[1. 1. 4.]
 [2. 2. 3.]]
Type is <type 'numpy.ndarray'>
Shape is (10, 2, 3)
Values are: 
[[[1.003638   1.034767   4.034274  ]
  [2.0984607  2.0173953  3.0970352 ]]

 [[0.947031   0.9405322  3.9047017 ]
  [1.8900365  1.9222978  2.7954485 ]]

 [[1.0069187  0.94272375 3.9289768 ]
  [1.9174387  1.7504319  2.8409815 ]]

 [[1.014997   0.8800684  3.93275   ]
  [1.9404083  1.8023666  2.9864943 ]]

 [[0.9967495  1.062624   4.031016  ]
  [2.060107   1.9758348  3.1553822 ]]

 [[1.079102   0.9176487  3.9996762 ]
  [1.9014931  1.8372334  2.8007765 ]]

 [[0.97245294 0.9941602  4.0634327 ]
  [2.1096203  2.0608516  3.077416  ]]

 [[1.0550686  0.96313435 3.7293746 ]
  [2.2170184  2.1987681  2.8864982 ]]

 [[1.074531   0.9909342  3.9091427 ]
  [1.9888587  1.8692344  2.6392128 ]]

 [[1.058092   1.0653477  3.9613786 ]
  [2.0442424  2.0110605  3.1510553 ]]]


In [9]:
print_np( x[:,0].transpose() )

Type is <type 'numpy.ndarray'>
Shape is (3,)
Values are: 
[5.78497801 1.11715573 6.10046508]


In [10]:
a = np.ones((2,3,5,7))
print_np(a)
print_np( np.reshape(a,(70,3)))

Type is <type 'numpy.ndarray'>
Shape is (2, 3, 5, 7)
Values are: 
[[[[1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1.]]]


 [[[1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1.]]]]
Type is <type 'numpy.ndarray'>
Shape is (70, 3)
Values are: 
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1

In [11]:
np.random.randint(10,size=3)

array([8, 5, 9])

In [12]:
input_x = tf.placeholder(tf.float32, [None,23,2,3])
print np.shape(input_x)[2]

2
